# Generated by Django 5.0.2 on 2024-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("mobile_number", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=320)),
            ],
        ),
    ]
